In [128]:
# Import Needed Packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [129]:
# load in the csvs for the analysis

WNV = pd.read_csv('Datasets/west_nile/input/train.csv') 
# spray = pd.read_csv('Datasets/west_nile/input/spray.csv')
weather = pd.read_csv('Datasets/west_nile/input/weather.csv')

In [130]:
# Look at present columns

print WNV.columns
print weather.columns

Index([u'Date', u'Address', u'Species', u'Block', u'Street', u'Trap',
       u'AddressNumberAndStreet', u'Latitude', u'Longitude',
       u'AddressAccuracy', u'NumMosquitos', u'WnvPresent'],
      dtype='object')
Index([u'Station', u'Date', u'Tmax', u'Tmin', u'Tavg', u'Depart', u'DewPoint',
       u'WetBulb', u'Heat', u'Cool', u'Sunrise', u'Sunset', u'CodeSum',
       u'Depth', u'Water1', u'SnowFall', u'PrecipTotal', u'StnPressure',
       u'SeaLevel', u'ResultSpeed', u'ResultDir', u'AvgSpeed'],
      dtype='object')

In [164]:
# Convert to datetime for merging
WNV.Date = pd.to_datetime(WNV['Date'])
weather.Date = pd.to_datetime(weather['Date'])

In [146]:
# Create Mask to Pick Appropriate Columns for Analysis
wnv_mask = ['Date', 'Address', 'Block', 'Street', 'Latitude', 'Longitude', 'WnvPresent']
weather_mask = ['Date', 'DewPoint', 'WetBulb', 'PrecipTotal', 'SeaLevel', 'Tmax', 'StnPressure']

In [153]:
wnv_merge = pd.merge(WNV[wnv_mask], weather[weather_mask], how='left', on='Date')

In [154]:
# Drop duplicates that remain as artefacts of the inital merge
wnv_ = wnv_merge.drop_duplicates()

In [155]:
wnv_.shape

(9848, 13)

In [159]:
# See if there are any null values (not counting 'm' or 't' values)
wnv_merge.isnull().sum()

Date           0
Address        0
Block          0
Street         0
Latitude       0
Longitude      0
WnvPresent     0
DewPoint       0
WetBulb        0
PrecipTotal    0
SeaLevel       0
Tmax           0
StnPressure    0
dtype: int64

In [161]:
wnv_.to_csv('WNV.csv')

In [162]:
WNV = pd.read_csv('WNV.csv')

In [163]:
WNV.dtypes

Unnamed: 0       int64
Date            object
Address         object
Block            int64
Street          object
Latitude       float64
Longitude      float64
WnvPresent       int64
DewPoint         int64
WetBulb         object
PrecipTotal     object
SeaLevel       float64
Tmax             int64
StnPressure     object
dtype: object

In [114]:
def trace(df, x):
    df[x] = df[x].apply(lambda x: x == np.NaN if x == 'M' else x)
    df[x] = df[x].apply(lambda x: x == 0.01 if x in ['T', '  T'] else x)
    df[x] = pd.to_numeric(df[x])
    return df

In [ ]:
x= ['']

In [21]:
WNV.WetBulb = WNV.WetBulb.apply(lambda x: x == np.NaN if x == 'M' else x)

In [22]:
WNV.WetBulb = pd.to_numeric(WNV.WetBulb)

In [23]:
WNV.PrecipTotal = WNV.PrecipTotal.apply(lambda x: x == np.NaN if x == 'M' else x)

In [24]:
WNV.PrecipTotal = WNV.PrecipTotal.apply(lambda x: x == 0.01 if x in ['T', '  T'] else x)

In [25]:
WNV.PrecipTotal = pd.to_numeric(WNV.PrecipTotal)

In [26]:
WNV.isnull().sum()

Unnamed: 0     0
Date           0
Address        0
Block          0
Street         0
Latitude       0
Longitude      0
WnvPresent     0
DewPoint       0
WetBulb        0
PrecipTotal    0
SeaLevel       0
dtype: int64

In [27]:
WNV.dropna(axis=0, how='any')

,Unnamed: 0,Date,Address,Block,Street,Latitude,Longitude,WnvPresent,DewPoint,WetBulb,PrecipTotal,SeaLevel
0,0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",41,N OAK PARK AVE,41.954690,-87.800991,0,58,False,0.0,30.11
1,1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",41,N OAK PARK AVE,41.954690,-87.800991,0,59,False,0.0,30.09
2,4,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",62,N MANDELL AVE,41.994991,-87.769279,0,58,False,0.0,30.11
3,5,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",62,N MANDELL AVE,41.994991,-87.769279,0,59,False,0.0,30.09
4,6,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",79,W FOSTER AVE,41.974089,-87.824812,0,58,False,0.0,30.11
5,7,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",79,W FOSTER AVE,41.974089,-87.824812,0,59,False,0.0,30.09
6,10,2007-05-29,"1500 West Webster Avenue, Chicago, IL 60614, USA",15,W WEBSTER AVE,41.921600,-87.666455,0,58,False,0.0,30.11
7,11,2007-05-29,"1500 West Webster Avenue, Chicago, IL 60614, USA",15,W WEBSTER AVE,41.921600,-87.666455,0,59,False,0.0,30.09
8,12,2007-05-29,"2500 West Grand Avenue, Chicago, IL 60654, USA",25,W GRAND AVE,41.891118,-87.654491,0,58,False,0.0,30.11
9,13,2007-05-29,"2500 West Grand Avenue, Chicago, IL 60654, USA",25,W GRAND AVE,41.891118,-87.654491,0,59,False,0.0,30.09
10,14,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",11,W ROOSEVELT,41.867108,-87.654224,0,58,False,0.0,30.11
11,15,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",11,W ROOSEVELT,41.867108,-87.654224,0,59,False,0.0,30.09
12,18,2007-05-29,"1100 West Chicago Avenue, Chicago, IL 60642, USA",11,W CHICAGO,41.896282,-87.655232,0,58,False,0.0,30.11
13,19,2007-05-29,"1100 West Chicago Avenue, Chicago, IL 60642, USA",11,W CHICAGO,41.896282,-87.655232,0,59,False,0.0,30.09
14,20,2007-05-29,"2100 North Stave Street, Chicago, IL 60647, USA",21,N STAVE ST,41.919343,-87.694259,0,58,False,0.0,30.11
15,21,2007-05-29,"2100 North Stave Street, Chicago, IL 60647, USA",21,N STAVE ST,41.919343,-87.694259,0,59,False,0.0,30.09
16,22,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",22,N CANNON DR,41.921965,-87.632085,0,58,False,0.0,30.11
17,23,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",22,N CANNON DR,41.921965,-87.632085,0,59,False,0.0,30.09
18,26,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",22,W 113TH ST,41.688324,-87.676709,0,58,False,0.0,30.11
19,27,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",22,W 113TH ST,41.688324,-87.676709,0,59,False,0.0,30.09
20,30,2007-05-29,"1100 South Peoria Street, Chicago, IL 60608, USA",11,S PEORIA ST,41.862292,-87.648860,0,58,True,0.0,30.11
21,31,2007-05-29,"1100 South Peoria Street, Chicago, IL 60608, USA",11,S PEORIA ST,41.862292,-87.648860,0,59,True,0.0,30.09
22,32,2007-05-29,"1700 West 95th Street, Chicago, IL 60643, USA",17,W 95TH ST,41.720848,-87.666014,0,58,True,0.0,30.11
23,33,2007-05-29,"1700 West 95th Street, Chicago, IL 60643, USA",17,W 95TH ST,41.720848,-87.666014,0,59,True,0.0,30.09
24,34,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",22,W 89TH ST,41.731922,-87.677512,0,58,False,0.0,30.11
25,35,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",22,W 89TH ST,41.731922,-87.677512,0,59,False,0.0,30.09
26,38,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",53,N STREETER DR,41.891126,-87.611560,0,58,False,0.0,30.11
27,39,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",53,N STREETER DR,41.891126,-87.611560,0,59,False,0.0,30.09
28,42,2007-05-29,"6500 North Oak Park Avenue, Chicago, IL 60631,...",65,N OAK PARK AVE,41.999129,-87.795585,0,58,True,0.0,30.11
29,43,2007-05-29,"6500 North Oak Park Avenue, Chicago, IL 60631,...",65,N OAK PARK AVE,41.999129,-87.795585,0,59,True,0.0,30.09
...,...,...,...,...,...,...,...,...,...,...,...,...
9709,20914,2013-09-26,"5000 South Union Avenue, Chicago, IL 60609, USA",50,S UNION AVE,41.803423,-87.642984,0,52,True,0.0,30.04
9710,20918,2013-09-26,"7900 South South Chicago Avenue, Chicago, IL 6...",79,S CHICAGO AVE,41.754292,-87.590773,0,52,True,0.0,30.04
9711,20920,2013-09-26,"5200 South Kolmar Avenue, Chicago, IL 60632, USA",52,S KOLMAR,41.798697,-87.736812,0,52,False,0.0,30.04
9712,20924,2013-09-26,"6300 West 64th Street, Chicago, IL 60638, USA",63,W 64TH ST,41.776156,-87.778927,1,52,False,0.0,30.04
9713,20926,2013-09-26,"3700 South Pulaski Road, Chicago, IL 60623, USA",37,S PULASKI RD,41.825610,-87.726549,0,52,False,0.0,30.04
9714,20928,2013-09-26,"South Doty Avenue, Chicago, IL, USA",12,S DOTY AVE,41.673408,-87.599862,0,52,False,0.0,30.04
9715,20932,2013-09-26,"South Stony Island Avenue, Chicago, IL, USA",10,S STONY ISLAND AVE,41.726465,-87.585413,0,52,False,0.0,30.04
9716,20936,2013-09-26,"South Brandon Avenue, Chicago, IL 60617, USA",13,S BRANDON,41.740641,-87.546587,0,52,False,0.0,30.04
9717,20942,2013-09-26,"3700 118th Street, Chicago, IL 60617, USA",37,E 118TH ST,41.680946,-87.535198,0,52,False,0.0,30.04
9718,20946,2013-09-26,"2400 East 105th Street, Chicago, IL 60617, USA",24,E 105TH ST,41.704572,-87.565666,0,52,False,0.0,30.04
9719,20950,2013-09-26,"8900 South Muskegon Avenue, Chicago, IL 60617,...",89,S MUSKEGON AVE,41.733643,-87.555510,0,52,False,0.0,30.04
9720,20952,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",10,S COTTAGE GROVE,41.750498,-87.605294,0,52,False,0.0,30.04
9721,20958,2013-09-26,"5800 North Pulaski Road, Chicago, IL 60646, USA",58,N PULASKI RD,41.984809,-87.728492,0,52,False,0.0,30.04
9722,20960,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",40,E 130TH ST,41.659112,-87.538693,0,52,False,0.0,30.04
9723,20966,2013-09-26,"9100 West Higgins Road, Rosemont, IL 60018, USA",91,W HIGGINS RD,41.992478,-87.862995,0,52,False,0.0,30.04
9724,20968,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",10,W OHARE AIRPORT,41.974689,-87.890615,1,52,False,0.0,30.04
9725,20970,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",10,W OHARE AIRPORT,41.974689,-87.890615,0,52,False,0.0,30.04
9726,20980,2013-09-26,"4800 West Montana Street, Chicago, IL 60639, USA",48,W MONTANA ST,41.925198,-87.746381,0,52,False,0.0,30.04
9727,20982,2013-09-26,"5100 North Mont Clare Avenue, Chicago, IL 6065...",51,N MONT CLARE AVE,41.973845,-87.805059,0,52,True,0.0,30.04
9728,20986,2013-09-26,"8200 South Kostner Avenue, Chicago, IL 60652, USA",82,S KOSTNER AVE,41.743402,-87.731435,0,52,True,0.0,30.04
9729,20988,2013-09-26,"East 91st Place, Chicago, IL, USA",65,E 91ST PL,41.728495,-87.600963,0,52,True,0.0,30.04
9730,20992,2013-09-26,"1700 West Addison Street, Chicago, IL 60613, USA",17,W ADDISON ST,41.947227,-87.671457,0,52,True,0.0,30.04
9731,20994,2013-09-26,"West Garfield Boulevard, Chicago, IL, USA",90,W GARFIELD BLVD,41.793818,-87.654234,0,52,True,0.0,30.04
9732,20996,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",13,N LARAMIE AVE,41.904194,-87.756155,0,52,False,0.0,30.04
9733,21000,2013-09-26,"3900 North Springfield Avenue, Chicago, IL 606...",39,N SPRINGFIELD AVE,41.951866,-87.725057,0,52,False,0.0,30.04
9734,21002,2013-09-26,"5100 West 72nd Street, Chicago, IL 60638, USA",51,W 72ND ST,41.763733,-87.742302,1,52,False,0.0,30.04
9735,21004,2013-09-26,"5800 North Ridge Avenue, Chicago, IL 60660, USA",58,N RIDGE AVE,41.987280,-87.666066,0,52,False,0.0,30.04
9736,21006,2013-09-26,"1700 North Ashland Avenue, Chicago, IL 60622, USA",17,N ASHLAND AVE,41.912563,-87.668055,0,52,False,0.0,30.04
9737,21008,2013-09-26,"7100 North Harlem Avenue, Chicago, IL 60631, USA",71,N HARLEM AVE,42.009876,-87.807277,0,52,False,0.0,30.04
9738,21010,2013-09-26,"4200 West 65th Street, Chicago, IL 60621, USA",42,W 65TH ST,41.776428,-87.627096,0,52,False,0.0,30.04

In [28]:
mask = ['WnvPresent', 'DewPoint', 'WetBulb', 'PrecipTotal', 'SeaLevel']

WNV[mask] = WNV[mask].fillna(WNV.mean())

In [29]:
WNV.WnvPresent = WNV.WnvPresent.apply(lambda x: x == 0 if x not in [0,1] else x)

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import train_test_split

In [61]:
lr = LogisticRegression()

params = {
    'C' : np.logspace(-2, 2, 50),
    'solver': ['liblinear'],
    'penalty' :['l1', 'l2']
}

In [119]:
Y = np.ravel(WNV['WnvPresent'])
X = WNV[['DewPoint', 'WetBulb', 'PrecipTotal', 'SeaLevel']]

In [68]:
X_train, x_test, Y_train, y_test = train_test_split(X, Y, test_size = 0.3)

In [64]:
gs = GridSearchCV(lr, params, cv=5 )

In [69]:
gs.fit(X_train, 
       Y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': array([  1.00000e-02,   1.20679e-02,   1.45635e-02,   1.75751e-02,
         2.12095e-02,   2.55955e-02,   3.08884e-02,   3.72759e-02,
         4.49843e-02,   5.42868e-02,   6.55129e-02,   7.90604e-02,
         9.54095e-02,   1.15140e-01,   1.38950e-01,   1.6...7e+01,   5.68987e+01,   6.86649e+01,
         8.28643e+01,   1.00000e+02]), 'solver': ['liblinear']},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [42]:
test = pd.read_csv('../Cojasami/Datasets/test.csv')

In [81]:
test.shape

(116293, 11)

In [72]:
preds = gs.predict(x_test)

In [73]:
from sklearn.metrics import confusion_matrix

In [75]:
confusion_matrix(y_test, preds)

array([[2683,    0],
       [ 239,    0]])

In [82]:
test.head()

,Id,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy
0,1,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
1,2,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
2,3,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
3,4,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX SALINARIUS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
4,5,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX TERRITANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9

In [98]:
test.Date = pd.to_datetime(test['Date'])

In [100]:
test_merge = pd.merge(test[['Date', 'Block', 'Latitude', 'Longitude']], weather[weather_mask], how='left', on='Date')

In [115]:
trace(test_merge, 'WetBulb')
trace(test_merge, 'PrecipTotal')

test_merge.dtypes

Date           datetime64[ns]
Block                   int64
Latitude              float64
Longitude             float64
DewPoint                int64
WetBulb                 int64
PrecipTotal           float64
SeaLevel               object
dtype: object

In [117]:
gs.predict_proba(test_merge[['DewPoint', 'Block', 'WetBulb', 'PrecipTotal', 'SeaLevel']])

array([[ 0.93336263,  0.06663737],
       [ 0.93547984,  0.06452016],
       [ 0.93336263,  0.06663737],
       ...,
       [ 0.91231184,  0.08768816],
       [ 0.9181626 ,  0.0818374 ],
       [ 0.91231184,  0.08768816]])

In [150]:
test_merge[test_merge['Block']==41]

,Date,Block,Latitude,Longitude,DewPoint,WetBulb,PrecipTotal,SeaLevel
0,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
1,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
2,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
3,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
4,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
5,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
6,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
7,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
8,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
9,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
10,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
11,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
12,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
13,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
14,2008-06-11,41,41.95469,-87.800991,56,64,0.00,29.99
15,2008-06-11,41,41.95469,-87.800991,55,64,0.00,29.97
2416,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.97
2417,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.96
2418,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.97
2419,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.96
2420,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.97
2421,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.96
2422,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.97
2423,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.96
2424,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.97
2425,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.96
2426,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.97
2427,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.96
2428,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.97
2429,2008-06-17,41,41.95469,-87.800991,46,55,0.00,29.96
...,...,...,...,...,...,...,...,...
227736,2014-09-25,41,41.95469,-87.800991,52,58,0.00,30.25
227737,2014-09-25,41,41.95469,-87.800991,54,59,0.00,30.24
227738,2014-09-25,41,41.95469,-87.800991,52,58,0.00,30.25
227739,2014-09-25,41,41.95469,-87.800991,54,59,0.00,30.24
227740,2014-09-25,41,41.95469,-87.800991,52,58,0.00,30.25
227741,2014-09-25,41,41.95469,-87.800991,54,59,0.00,30.24
227742,2014-09-25,41,41.95469,-87.800991,52,58,0.00,30.25
227743,2014-09-25,41,41.95469,-87.800991,54,59,0.00,30.24
227744,2014-09-25,41,41.95469,-87.800991,52,58,0.00,30.25
227745,2014-09-25,41,41.95469,-87.800991,54,59,0.00,30.24
227746,2014-09-25,41,41.95469,-87.800991,52,58,0.00,30.25
227747,2014-09-25,41,41.95469,-87.800991,54,59,0.00,30.24
227748,2014-09-25,41,41.95469,-87.800991,52,58,0.00,30.25
227749,2014-09-25,41,41.95469,-87.800991,54,59,0.00,30.24
230170,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230171,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78
230172,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230173,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78
230174,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230175,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78
230176,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230177,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78
230178,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230179,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78
230180,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230181,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78
230182,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230183,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78
230184,2014-10-02,41,41.95469,-87.800991,61,63,0.32,29.78
230185,2014-10-02,41,41.95469,-87.800991,63,65,0.72,29.78